# .github/workflows/static.yml

name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches: ["main"] # Altere para sua branch principal se não for 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a versão do Node.js que você usa no seu projeto (ex: '18', '20')
          cache: 'npm'       # ou 'yarn', 'pnpm' dependendo do seu gerenciador de pacotes

      - name: Instalar Dependências
        run: npm install --force # ou 'yarn install', 'pnpm install'

      - name: Fazer o Build do Projeto Vite
        run: npm run build # ou 'yarn build', 'pnpm build'

      - name: Upload do Artefato de Build
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Caminho para a pasta de build do Vite

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
